### ISSUE TITLE
find_open_cases_for_plan

### ISSUE THREAD

**Issue by fishstick** [turboladen/test_linker#12]
Because find_test_plan was fixed/changed, it now always returns an array even for a single object. This breaks find_open_cases_for_plan :
/home/qa/.rvm/gems/ree-1.8.7-head@dps_qc/gems/test_linker-1.0.1/lib/test_linker/helpers.rb:195:in `[]': Symbol as array index (TypeError)
    from /home/qa/.rvm/gems/ree-1.8.7-head@dps_qc/gems/test_linker-1.0.1/lib/test_linker/helpers.rb:195:in`find_open_cases_for_plan'
    from /home/qa/.rvm/gems/ree-1.8.7-head@dps_qc/gems/vatf_core-1.0.18/lib/vatf_core.rb:83:in `collect_testlink_cases'
    from /home/qa/.rvm/gems/ree-1.8.7-head@dps_qc/gems/vatf_core-1.0.18/bin/picker:55
    from /home/qa/.rvm/gems/ree-1.8.7-head@dps_qc/bin/picker:19:in`load'
    from /home/qa/.rvm/gems/ree-1.8.7-head@dps_qc/bin/picker:19

the fix is rather easy:

<  test_plans = find_test_plans(project_id, plan_regex) # Get plans for project

>  test_plans = find_test_plans(project_id, plan_regex).first # Get plans for project

**Comment by turboladen** [comment]
Hmm... yeah, good bug find.  This introduces some inconsistencies, for sure.

Currently `#find_open_cases_for_plan` takes a `Regexp` as the 2nd parameter--that alone implies that you could match more than 1 test plan (and then calling `#first` would, of course, always just return the first result from the match set, and thus probably cause some unexpected behavior).  If that's the case, then this should really be `#find_open_cases_for_plans` (plural).  If a user is more likely to want to search for open cases for a single plan, then the 2nd param of `#find_open_cases_for_plan` should probably be a `String` (which implies a single match).

Do you have a preference as to whether this method should be for a group of test plans or a single test plan?  I'm also considering just doing both...

**Comment by fishstick** [comment]
Yeah, .first is a really dirty fix. 

For me it would make more sense to rename it to find_open_cases_for_plan and raise/error if multiple are matched. I don't have any real preference though, so if you want to do both that's just as good for me! :).
